### PR TITLE
Add Docker Compose file and update README

### LINKED ISSUE #57: Add docker-compose file for development
A docker-compose file should be added to be used for development and testing.

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #57 

To see the updated README go [here](https://github.com/EMMC-ASBL/oteapi-plugin-template/tree/cwa/close-57-docker-compose-dev#readme).

### CODE REVIEW

**Comment by sygout** [comment]
Looks nice. but 2 questions:
 - it seems that the text is duplicated. why? it is possible to use a reference?
 - sentence : " Note, remember to update [`setup.cfg`](setup.cfg) to list the plugin strategies - otherwise they will not be findable by the OTEAPI service." is it specific to the service test or a generic remark for the plug-in development?

**Comment by CasperWA** [comment]
> * it seems that the text is duplicated. why? it is possible to use a reference?

Which text do you mean explicitly?

> * sentence : " Note, remember to update [`setup.cfg`](setup.cfg) to list the plugin strategies - otherwise they will not be findable by the OTEAPI service." is it specific to the service test or a generic remark for the plug-in development?

This is how the plugin system works - so this is general.

**Comment by sygout** [comment]
text in these two files:
{{ cookiecutter.project_slug }}/docs/index.md 
{{ cookiecutter.project_slug }}/README.md

"This is how the plugin system works - so this is general." then i would put it at the start of the Test the plugin section. So that it is more visible

Otherwise I see that a CI test if failing.

**Comment by CasperWA** [comment]
> text in these two files: {{ cookiecutter.project_slug }}/docs/index.md {{ cookiecutter.project_slug }}/README.md
> 
> "This is how the plugin system works - so this is general." then i would put it at the start of the Test the plugin section. So that it is more visible
> 
> Otherwise I see that a CI test if failing.

Ah - the `index.md` file is generated from the `README.md`. Hence the similar text :)
One is essentially a copy of the other, with some tricks to fix the links.

**Comment by CasperWA** [comment]
> Ah - the `index.md` file is generated from the `README.md`. Hence the similar text :) One is essentially a copy of the other, with some tricks to fix the links.

For more information on how this is done, see the [pre-commit hooks config file](https://github.com/EMMC-ASBL/oteapi-plugin-template/blob/master/%7B%7B%20cookiecutter.project_slug%20%7D%7D/.pre-commit-config.yaml#L77:L84) and the associated [invoke task](https://github.com/EMMC-ASBL/oteapi-plugin-template/blob/master/%7B%7B%20cookiecutter.project_slug%20%7D%7D/tasks.py#L174:L190).

Note that the latter has been updated in the current PR.

**Review by sygout — APPROVED** [review]

**Pull request merged**
